name: fe
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  flutter_chat_bubble: ^2.0.0
  url_launcher: ^6.0.18

  flutterfire_ui: ^0.4.0+4

  image_picker: ^0.8.4+6

  extended: ^0.1.5

  flutter_app_badger: ^1.3.0

  fireflutter:
    path: ..

  audioplayers: ^1.0.0-rc.1

  font_awesome_flutter:
    path: ./lib/packages/font_awesome_flutter

  map_launcher: ^2.2.2

dependency_overrides:
  font_awesome_flutter:
    path: ./lib/packages/font_awesome_flutter

  cached_network_image:
    git:
      url: https://github.com/XuannThucc/flutter_cached_network_image.git
      path: cached_network_image
      ref: ff72f00f142f13d889d7549e013af91cb0b523ab

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/click.mp3
